name: TodoWorkflow
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
      security-events: write
      statuses: write
    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies for Backend
        run: |
          cd backend
          npm install

      - name: Install Dependencies for Frontend
        run: |
          cd frontend
          npm install

      - name: Run Prepare (Instrumentation) for Frontend
        run: |
          cd frontend
          npm run prepare

      - name: Start Server
        run: |
          cd backend
          npm run starttest &
        env:
          PORT: 3000

      - name: Run Tests & Coverage for Frontend
        id: frontend-tests
        run: |
          cd frontend
          npm test
        continue-on-error: true

      - name: Run SonaCube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Upload Cypress Test Results as Artifacts
        if: always() # Damit die Artefakte auch bei einem fehlgeschlagenen Test hochgeladen werden
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            frontend/cypress/videos
            frontend/cypress/screenshots
            frontend/cypress/coverage

      - name: Fail Workflow if Frontend Tests Failed
        if: steps.frontend-tests.outcome == 'failure'
        run: exit 1
